service: odb # Replace with your desired service name
provider:
  name: aws
  runtime: nodejs14.x
  profile: htognia
functions:
  getItem:
    handler: lambdas/getSingleCompetition.getItem
    events:
      - http:
          path: getitem
          method: Get
          cors: true

  getCompetitions:
    handler: lambdas/getCompetitions.getItems
    events:
      - http:
          path: getcompetitions
          method: get
          cors: true
