service: odb-api # Replace with your desired service name
provider:
  name: aws
  runtime: nodejs14.x
  profile: htognia
  stage: ${opt:stage, 'dev'}
  apiId: ${opt:apiId, 'ymumz18hhl'}
  environment:
    STAGE: ${self:provider.stage}
    API_ID: ${self:provider.apiId}
  
functions:
  competition:
    handler: lambdas/competition.getItem
    events:
      - http:
          path: competitions/{id}
          method: Get
          cors: true
          authorizer: authorizerFunc

  competitions:
    handler: lambdas/competitions.getItems
    events:
      - http:
          path: competitions
          method: get
          cors: true
          authorizer: authorizerFunc
  authorizerFunc:
    handler: authorizer/competitions.authorizer
  

