service: odb-api # Replace with your desired service name
provider:
  name: aws
  runtime: nodejs14.x
  profile: htognia
  
functions:
  competition:
    handler: lambdas/competition.getItem
    events:
      - http:
          path: competitions/{competitionId}
          method: Get
          cors: true
          authorizer: authorizerFunc

  competitions:
    handler: lambdas/competitions.getItems
    events:
      - http:
          path: competitions
          method: get
          cors: true
          authorizer: authorizerFunc
  authorizerFunc:
    handler: authorizer/competitions.authorizer
  

